import {
  apply,
  cwlRoster,
  recruiterScore,
  ro,
  cwlQuestions,
  closeTicket,
  deleteTicket,
  createEvent,
  scheduleEvent,
  eventWinner,
  nominate,
  nominationResult,
  rankProposalReminder,
  questionCreate,
  questionClose,
  questionAnswer,
  eventLeaderboard,
  deleteEvent,
  rewardClaimed,
} from './commands';

export const tcnCommands = [
  apply,
  cwlRoster,
  ro,
  recruiterScore,
  cwlQuestions,
  closeTicket,
  deleteTicket,
  createEvent,
  scheduleEvent,
  questionCreate,
  questionClose,
  questionAnswer,
  eventLeaderboard,
  eventWinner,
  rewardClaimed,
  deleteEvent,
  nominate,
  nominationResult,
  rankProposalReminder,
];
