import {
  apply,
  cwlRoster,
  recruiterScore,
  ro,
  cwlQuestions,
  closeTicket,
  deleteTicket,
  createEvent,
  eventWinner,
  nominate,
  nominationResult,
  rankProposalReminder,
  questionCreate,
  questionClose,
  questionAnswer,
  eventLeaderboard,
} from "./commands";

export const tcnCommands = [
  apply,
  cwlRoster,
  ro,
  recruiterScore,
  cwlQuestions,
  closeTicket,
  deleteTicket,
  createEvent,
  questionCreate,
  questionClose,
  questionAnswer,
  eventLeaderboard,
  eventWinner,
  nominate,
  nominationResult,
  rankProposalReminder,
];
