name: Pipeline

on:
  push:
    paths:
      - infra/**
      - bot/**
      - ui/**
      - .github/workflows/deploy.yml
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

env:
    DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
    CLASH_API_TOKEN: ${{ secrets.CLASH_API_TOKEN }}
    BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: us-east-1

      - run: npm install

      - run: npm run build --workspace bot

      - run: npm test

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: npm run deploy --workspace infra -- --require-approval never
